Feature/venue info map gp81v2
GatherPress/gatherpress pull request #226
Opened 2023-01-09 15:26 UTC by pbrocks

This PR addresses Feature 2 of [Venue issue](https://github.com/GatherPress/gatherpress/issues/81)

2023-01-13 15:38 UTC, pbrocks commented
![image](https://user-images.githubusercontent.com/5721313/212358693-b956560c-cc6b-4675-8be9-4e88832a17af.png)

forgot to rebuild

2023-01-13 16:57 UTC, mauteri approved these changes

2023-01-13 16:57 UTC, mauteri commented on src/blocks/venue-information/style.scss
> +        justify-content: space-between;
fix indent

2023-01-13 19:12 UTC, pbrocks commented on src/blocks/venue-information/style.scss
> +        justify-content: space-between;
![image](https://user-images.githubusercontent.com/5721313/212399896-5f8a0a55-7e47-4fb6-9840-48a4c6a620d7.png)

So elfin annoying!!!

2023-01-15 03:43 UTC, mauteri requested changes
Following other PR, can this one be closed?

2023-01-16 20:48 UTC, pbrocks commented
> Following other PR, can this one be closed?

Absolutely this should be closed.

2023-01-16 20:48 UTC, closed without merging