Integrated new feature which allows users to decline attending immedi…
GatherPress/gatherpress pull request #567
Opened 2024-02-25 00:01 UTC by stephenerdelyi

### Description of the Change
Need a feature that allows a user to set themselves as "Not Attending" right from the start.
Make this setting a toggled feature that is both global as well as an event specific (to override global)

Closes https://github.com/GatherPress/gatherpress/issues/534

### How to test the Change
Create new event (or edit existing). Select "RSVP" block in backend and check the new box titled "Allow attendees to select 'not attending' immediately". Navigate to plugin settings and test the new global option as well.

### Changelog Entry
> Added - Allow users to decline attending immediately

### Credits
Props @stephenerdelyi 

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

2024-02-28 02:00 UTC, mauteri requested changes

2024-02-29 08:22 UTC, stephenerdelyi commented on includes/core/classes/class-event.php
> +	public static function get_post_type_registration_args(): array {
Done! Thanks for the heads up, made it way easier when I got in there and saw it 👍

2024-02-29 08:22 UTC, stephenerdelyi commented on includes/core/classes/class-event.php
> +	public static function get_taxonomy_registration_args(): array {
Done!

2024-02-29 08:45 UTC, stephenerdelyi commented
Hey @mauteri, this is ready for your review once again! Thanks for your patience.

2024-03-02 01:41 UTC, mauteri approved these changes

2024-03-02 01:41 UTC, merged