Issue 571: Added Maximum Attending Limit at the event level.
GatherPress/gatherpress pull request #581
Opened 2024-03-01 06:41 UTC by bluecollarcoders

### Description of the Change

Closes #571 

### How to test the Change

In the event setting  you will see a panel body labeled Maximum Attending Limit

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-03-01 13:37 UTC, mauteri requested changes

2024-03-01 13:37 UTC, mauteri commented on includes/core/classes/class-assets.php
> +				'maxAttendance'       => (int) get_post_meta( $post_id, 'max_attendance', true ),
Let's change this everywhere to `maxAttendanceLimit` and `max_attendance_limit`. Looks good though!

2024-03-01 13:39 UTC, mauteri requested changes

2024-03-01 13:39 UTC, mauteri commented on src/components/MaxAttendance.js
> +	let defaultMaxAttendance = useSelect((select) => {
`defaultMaxAttendanceLimit`

2024-03-01 13:39 UTC, mauteri commented on src/components/MaxAttendance.js
> +	const [maxAttendance, setMaxAttendance] = useState(null);
```
const [maxAttendanceLimit, setMaxAttendanceLimit] = useState(defaultMaxAttendanceLimit);
```

2024-04-01 04:40 UTC, bluecollarcoders commented
@mauteri I updated the PR, but it says there are conflicts with the branch. I did a git pull and I had no conflicts with the branch.

2024-04-01 13:23 UTC, mauteri commented
@bluecollarcoders make sure on your forked repo you sync main with your main then pull that down to your branch. you'll also need to run `npm install` with the latest version of node in `.npmrc` and `npm run build`. Let me know if you have any other questions. Thx!

2024-04-01 19:27 UTC, mauteri requested changes
Just a few small things and I think this will be good. Thx @bluecollarcoders!

2024-04-01 19:27 UTC, mauteri commented on includes/core/classes/class-assets.php
> -				'enableInitialDecline' => (bool) get_post_meta( $post_id, 'enable_initial_decline', true ),
This one shouldn't have been removed.

2024-04-01 19:27 UTC, mauteri commented on includes/core/classes/class-assets.php
> -				'enableInitialDecline' => ( 1 === (int) $settings->get_value( 'general', 'general', 'enable_initial_decline' ) ),
same with this one.

2024-04-01 19:27 UTC, mauteri commented on src/components/MaxAttendanceLimit.js
> +			.max_attendance;
this should be `.max_attendance_limit`.

2024-04-01 19:27 UTC, mauteri commented on src/components/MaxAttendanceLimit.js
> +		defaultMaxAttendanceLimit = getFromGlobal('settings.maxAttendance');
`defaultMaxAttendanceLimit = getFromGlobal('settings.maxAttendanceLimit');`

2024-04-01 19:27 UTC, mauteri commented on src/components/MaxAttendanceLimit.js
> +			label={__('Maximum Attending Limit', 'gatherpress')}
`Maximum Attendance Limit` for consistency.

2024-04-27 19:57 UTC, mauteri requested changes

2024-04-27 19:57 UTC, mauteri commented on includes/core/classes/class-assets.php
> +				'maxAttendanceLimit'   => (int) get_post_meta( $post_id, 'max_attendance_limit', true ),
My PR merged, so let's update this.
```
'maxAttendanceLimit'   => (int) get_post_meta( $post_id, 'gatherpress_max_attendance_limit', true ),
```

2024-04-27 19:57 UTC, mauteri commented on src/components/MaxAttendanceLimit.js
> +			.max_attendance_limit;
```
.gatherpress_max_attendance_limit;
```

2024-05-19 20:58 UTC, mauteri commented
Merging this, thx @bluecollarcoders! I opened a ticket with `wordpress-version-checker` on this issue https://github.com/skaut/wordpress-version-checker/issues/1193 (cc @carstingaxion @jeffpaul)

2024-05-19 20:59 UTC, merged