Add Readme section for 3rd party software
GatherPress/gatherpress pull request #658
Opened 2024-05-11 12:07 UTC by jmarx

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-05-11 16:06 UTC, stephenerdelyi requested changes
Do we need to add the following?
- [Google Maps](https://developers.google.com/maps): Used to render maps - only when Google Maps is selected as your mapping platform.
- [Open Street Map](https://www.openstreetmap.org/): Used to render maps - only when Open Street Map is selected as your mapping platform.

2024-05-11 17:36 UTC, jmarx commented
> Do we need to add the following?
> 
> * [Google Maps](https://developers.google.com/maps): Used to render maps - only when Google Maps is selected as your mapping platform.
> * [Open Street Map](https://www.openstreetmap.org/): Used to render maps - only when Open Street Map is selected as your mapping platform.

@stephenerdelyi  I was going to add OSM as part of our OSM feature. I'm not sure if we need to add google maps since we are just iframing their map. What do you think @mauteri ? Also, does anyone know why the a php unit test would be failing on a simple readme change?

2024-05-11 20:45 UTC, carstingaxion commented
> Also, does anyone know why the a php unit test would be failing on a simple readme change?

@jmarx the logs know the answer, "they" said:

> Could not connect to deb.debian.org:80 (146.75.94.132), connection timed out

Should probably work on the next run.

2024-05-13 00:07 UTC, jmarx commented
@mauteri Are we good to merge this? Or should we add the map items?

2024-05-13 13:19 UTC, carstingaxion commented
I added all the changes also to #653 .

2024-05-14 13:27 UTC, mauteri requested changes

2024-05-14 13:27 UTC, mauteri commented on README.md
> +- [Playwright](https://playwright.dev/): Enables browser automation for testing and interaction.
Not needed here as it is not packaged with the plugin

2024-05-14 13:30 UTC, mauteri requested changes

2024-05-18 19:31 UTC, closed without merging

2024-05-18 19:31 UTC, mauteri commented
Closing this PR as this should be done in @carstingaxion's PR at this point.