Update readme.md
GatherPress/gatherpress pull request #866
Opened 2024-09-09 13:32 UTC by pbrocks

Add information about Playground and containerizing paragraphs. The thought here is that providing heading  should provide links as well as making lifting sections easier down the line, e.g. the Pilot Program.

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-09-11 13:33 UTC, mauteri requested changes

2024-09-11 13:33 UTC, mauteri commented on readme.md
> +Contributors: mauteri, hrmervin, patricia70, carstenbach, jmarx75, stephenerdelyi, calebthedev, pbrocks, prayagm, linusx007
This is handled by a script, we don't manually update this.

2024-09-12 01:25 UTC, patriciabt commented
Nice thanks a lot. See #805 as well

Additionally, I would also like this modified:
`[@Patricia BT](https://profiles.wordpress.org/patricia70/) in January 2024 on [make.wordpress.org](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)`
to
`Our proposal in January 2024 on [make.wordpress.org](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)`

2024-09-12 15:12 UTC, pbrocks commented
> Nice thanks a lot. See #805 as well
> 
> Additionally, I would also like this modified: `[@Patricia BT](https://profiles.wordpress.org/patricia70/) in January 2024 on [make.wordpress.org](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)` to `Our proposal in January 2024 on [make.wordpress.org](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)`

Updated this

2024-09-12 15:51 UTC, mauteri approved these changes

2024-09-12 15:51 UTC, merged