NEW unit tests for the Import & Export classes
GatherPress/gatherpress pull request #937
Opened 2024-10-04 22:46 UTC by carstingaxion

### Description of the Change

~~Closes #~~

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-10-04 22:49 UTC, carstingaxion commented
Hello @mauteri ,

can you please help me here, please?

I'm wondering if the failing unit-test should be _fixed_ rather in `class-import.php` or maybe better in `class-event.php` as it could be helpful to check if the needed array keys exist before saving.

What do you think?

2024-10-10 22:54 UTC, mauteri requested changes

2024-10-10 22:54 UTC, mauteri commented on includes/core/classes/class-export.php
> +	}
Let's add this to the new `Validate` class. `Validate::event_post_type( $post )`

https://github.com/GatherPress/gatherpress/blob/develop/includes/core/classes/class-validate.php

2024-10-10 22:54 UTC, mauteri commented on test/unit/php/includes/core/classes/class-test-export.php
> +		);
There's a helper to do this. Example [here](https://github.com/GatherPress/gatherpress/blob/develop/test/unit/php/includes/core/classes/class-test-block.php#L30).

2024-10-10 23:44 UTC, mauteri commented on includes/core/classes/class-export.php
> +	}
never mind, we can use `Validate::event_post_id` here.

2024-10-10 23:45 UTC, mauteri approved these changes

2024-10-10 23:45 UTC, merged