Introduce files from https://github.com/carstingaxion/additional-adva…
GatherPress/gatherpress pull request #962
Opened 2024-11-19 10:34 UTC by carstingaxion

…nced-query-loops/tree/gatherpress-query-loop (https://github.com/GatherPress/gatherpress/issues/599)

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/GatherPress/gatherpress/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2025-07-07 09:49 UTC, carstingaxion commented
I'm sorry, this took so long, is not well described and was not a very „friendly“ PR for anyone to contribute to.

I’m willing to finish this, if it’s not already obsolete because you did something better in the last couple of months.

Let me know if you (as the GatherPress community) are still interested in this piece of code?

2025-07-09 09:25 UTC, carstingaxion commented
I don't understand why its still conflicting at this point, locally I was able to merge my PR into _develop_ at https://github.com/GatherPress/gatherpress/commit/e4860316d1a48889633df15f75d5aa841ece51d0 without problems.

2025-07-09 09:36 UTC, carstingaxion commented
Heureka ....

2025-07-09 12:05 UTC, carstingaxion commented
https://github.com/user-attachments/assets/f9d3d9cd-46b3-4f59-a547-73c19acde37c

2025-07-09 13:56 UTC, mauteri commented
Awesome! If you're back on this one @carstingaxion I think we can get this into 0.33. Thanks!

2025-07-12 23:33 UTC, mauteri requested changes

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/event-order-controls.js
> +					// },
You can uncomment this, it does support Author now.

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/event-order-controls.js
> +					// },
remove commented code.

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/event-order-controls.js
> +					// },
remove commented code.

2025-07-12 23:33 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +			$secondary_day   = substr( $date_secondary, 8, 2 );
I don't love the use of `substr` here. I'd rather us use the `date` function to get the correct formatting from the provided date. Will be easier to understand and less prone to bugs.

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/post-date-query-controls.js
> +					{ label: 'Between', value: 'between' },
translate label text in options.

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/post-date-query-controls.js
> +					{relationFromQuery === 'between' && (
yoda syntax

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/post-date-query-controls.js
> +					{relationFromQuery === 'between' && (
yoda syntax

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/components/event-count-controls.js
> +};
Let's put all these in component file in one file `components.js`

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/controls.js
> +import { EventIncludeUnfinishedControls } from './components/event-include-unfinished-controls';
See note above about putting these all in one file.

2025-07-12 23:33 UTC, mauteri commented on src/variations/event-query/index.js
> +				],
We'll get a version of this released in 0.33 I think, but this innerBlocks area will need to be updated in 0.34 when we make changes to venue and online event blocks because those currently will not here in their current state.

2025-07-12 23:33 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +				$wp_query = new \WP_Query( $filtered_query_args ); // phpcs:ignore WordPress.WP.GlobalVariablesOverride.Prohibited
add a `use WP_Query` so you don't have to `\` it.

2025-07-12 23:33 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +			// "Hijack the global query. It's a hack, but it works." Ryan Welcher
Looks like this is a stray comment, you have it again below where you're overriding `$wp_query`

2025-07-12 23:44 UTC, mauteri commented
@carstingaxion left some initial notes on this. I would also go through and remove any commented out code to keep things tidy. Also unit tests and E2E tests are failing (make sure you're synced with latest from develop branch). Also was having trouble getting it to work in Playground. Seems there's a bunch of JS errors when sorting by event date. Let me know if you have any questions or comments on my notes. Thx!

2025-07-13 07:06 UTC, carstingaxion commented
Thanks for your comments @mauteri .

I did not want to do start any polishing until at least some people gave feedback.

2025-07-13 12:23 UTC, carstingaxion commented
> Also was having trouble getting it to work in Playground. Seems there's a bunch of JS errors when sorting by event date. Let me know if you have any questions or comments on my notes. Thx!

@mauteri Searching and searching and searching ....  to find this in the code

> Reverted this PR, but needs to be investigated again to work with Query block https://github.com/GatherPress/gatherpress/pull/889

....

2025-07-13 13:10 UTC, mauteri commented
> > Also was having trouble getting it to work in Playground. Seems there's a bunch of JS errors when sorting by event date. Let me know if you have any questions or comments on my notes. Thx!
> 
> @mauteri Searching and searching and searching .... to find this in the code
> 
> > Reverted this PR, but needs to be investigated again to work with Query block #889
> 
> ....
> 
> No wonder things didn't work anymore.

You can revert this PR and apply to your PR with this command
```
git revert bc7ecd9d83bc8de69167160bdc1683c97dc55555 -m 1
```
Then we can test Event List block as well and adjust the code to work in both places.

2025-07-13 15:02 UTC, carstingaxion commented
The remaining phpstan issue comes from the last recent change in #1118, which already seemed strange to me btw.

But more importantly, how do we find the mentioned sorting problem now @mauteri ?

2025-07-13 17:57 UTC, carstingaxion commented on src/variations/event-query/components/event-order-controls.js
> +					// },
Yes .... but, I can't imagine of any case, where ordering by author would be any usefull for events. If you can bring at least one scenario, for sure I could allow ordering by author here.

2025-07-13 18:00 UTC, carstingaxion commented on src/variations/event-query/components/event-count-controls.js
> +};
Excuse me, I don't want to be rude, but why?

Concatenation is done by the build scripts and for humans it's probably much easier in singular files.

2025-07-13 20:02 UTC, carstingaxion commented
> But more importantly, how do we find the mentioned sorting problem now @mauteri ?

I might have found, what could have been the problem. **Were the events in the event-list block in reverse order?**
This could be easily solved by adding the `order` parameter to the `WP_Query` at [`get_events_list()`](https://github.com/carstingaxion/gatherpress/blob/1602dc8e3194c194d1f628b892d4891157c1775a/includes/core/classes/class-event-query.php#L102), which I tested successfully.

Opinions @mauteri ??

2025-07-13 20:52 UTC, mauteri commented
> * **Normal** WordPress playground for PR#962

That seems to be the issue I see as well in Playground. Let's add that.

The Query Loop variants for Events appears to work now as well. thx!

2025-07-13 22:40 UTC, carstingaxion commented
Thanks for your last comment @mauteri , I would really appreciate you looking into the other open comments and question in this PR and your review!

2025-07-16 18:20 UTC, mauteri commented
You need to sync this branch from develop, build files are no longer committed and e2e will pass, though it needs a lot of work.

2025-07-16 18:58 UTC, carstingaxion commented
??? @mauteri 

It is synced.

What will need a lot of work, this branch?

2025-07-16 19:04 UTC, mauteri commented
> ??? @mauteri
> 
> It is synced.
> 
> What will need a lot of work, this branch?

Something isn't right. You shouldn't see `build` directory in PR. Should be ignored now. Also your E2E test is failing from timeout, which doesn't happen any more.

2025-07-16 19:11 UTC, mauteri commented
> > ??? @mauteri
> > It is synced.
> > What will need a lot of work, this branch?
> 
> Something isn't right. You shouldn't see `build` directory in PR. Should be ignored now. Also your E2E test is failing from timeout, which doesn't happen any more.

There was a cache. I think it's fixed now. Make sure to pull changes from your branch down.

2025-07-21 10:54 UTC, carstingaxion commented
Hello @mauteri , can you please answer my replies to your questions and suggestions here!

2025-07-21 13:44 UTC, mauteri commented
> Hello @mauteri , can you please answer my replies to your questions and suggestions here!

Hey @carstingaxion I answer everything I thought (I don't see any outstanding question). Also please don't put everything on me here. It is best to post any questions in the Slack where there are more people that can assist. Thanks!

2025-07-21 19:56 UTC, carstingaxion commented
Hello @mauteri, thanks for your fast reply!

> I answer everything I thought (I don't see any outstanding question). 

It looks different to me, allow me to add some screens of what I mean and like to get your opinion on:

1. <img width="1157" height="675" alt="image" src="https://github.com/user-attachments/assets/5e6cd8ab-66b6-494a-9df0-548dbbe24508" />

---

2. <img width="1157" height="635" alt="image" src="https://github.com/user-attachments/assets/6eed6428-25df-4258-b6e6-216f0de45400" />

---

3. <img width="1157" height="119" alt="image" src="https://github.com/user-attachments/assets/7c1f6db0-dd37-4ec6-9dbc-23dfe6cdead6" />

---

> Also please don't put everything on me here. 

I'm sorry for stressing you. I really tried to avoid putting everything on you, but unfortunately I had no luck with the following:

1. Asking also @MervinHernandez and @patriciabt for feedback in one of my first comments on this PR, with no luck.
2. Writing a comment on gatherpress.org on the weekly huddle 10 days ago, to gather more feedback from the whole team and everybody who might be interested, but this comment is still awaiting moderation.

> It is best to post any questions in the Slack where there are more people that can assist.

I'm not able to join the conversation on slack, due to some 🍍🍕🤡, sorry.

2025-07-21 20:12 UTC, carstingaxion commented
Hello @jmarx, @pbrocks, @stephenerdelyi, @bluecollarcoders, @jeffpaul, @01Prayag, @linusx, @prashantabellad, @JordanPak, @malgrauk, @ajskelton, @nilovelez, @shawfactor, @audunmb,

_at first:_ **Sorry for pinging you directly!**

I'm looking for feedback on the given PR and would absolutely love, if you could take the time to open this in Playground, experiment with the new "Event Query" block AND share your findings!

Thank you very much!

2025-07-21 21:02 UTC, mauteri commented on src/variations/event-query/components/event-count-controls.js
> +};
You're putting one function per file, seems overkill and could easily be put in one file without it being an excessively large file.

2025-07-21 21:02 UTC, mauteri commented on src/variations/event-query/components/event-order-controls.js
> +					// },
I don't feel strongly about it. In the case I would remove the code.

2025-07-21 21:02 UTC, mauteri commented on src/variations/event-query/components/event-order-controls.js
> +					// },
I could see a filter by author if 2 or more people are holding events for different groups of people on the same site.

2025-07-21 21:03 UTC, mauteri commented
> Hello @mauteri, thanks for your fast reply!
> 
> > I answer everything I thought (I don't see any outstanding question).
> 
> It looks different to me, allow me to add some screens of what I mean and like to get your opinion on:
> 
> 1. <img alt="image" width="1157" height="675" src="https://private-user-images.githubusercontent.com/198883/468783201-5e6cd8ab-66b6-494a-9df0-548dbbe24508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMzIwNjEsIm5iZiI6MTc1MzEzMTc2MSwicGF0aCI6Ii8xOTg4ODMvNDY4NzgzMjAxLTVlNmNkOGFiLTY2YjYtNDk0YS05ZGYwLTU0OGRiYmUyNDUwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyMVQyMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmI4ZjJlY2QyYjRkZDI4MDczYmFlNDI2OTdhNWE1YWJhZTYyMzkyMmQwNWQ0MThlMjgyODRhNzcwYTY5MDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2PK0BU-VjCPotVUmBFZvYre7GaGsoaCwmTwVVrVB-WY">
> 
> 2. <img alt="image" width="1157" height="635" src="https://private-user-images.githubusercontent.com/198883/468783615-6eed6428-25df-4258-b6e6-216f0de45400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMzIwNjEsIm5iZiI6MTc1MzEzMTc2MSwicGF0aCI6Ii8xOTg4ODMvNDY4NzgzNjE1LTZlZWQ2NDI4LTI1ZGYtNDI1OC1iNmU2LTIxNmYwZGU0NTQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyMVQyMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjZhNTAyY2I0NWFmNWI0NWYzZWNlYjE0MWM4OTFlZmFjYzE0OGMzNDAyMzlhNTI4MDc0N2NlNmRjNzI0YjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kDy_dg8O70GMncc5Y1waZspgqZQKQMm0OspbEPdZdKI">
> 
> 3. <img alt="image" width="1157" height="119" src="https://private-user-images.githubusercontent.com/198883/468784082-7c1f6db0-dd37-4ec6-9dbc-23dfe6cdead6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMzIwNjEsIm5iZiI6MTc1MzEzMTc2MSwicGF0aCI6Ii8xOTg4ODMvNDY4Nzg0MDgyLTdjMWY2ZGIwLWRkMzctNGVjNi05ZGJjLTIzZGZlNmNkZWFkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyMVQyMTAyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmJkMWVmNjJjNDVmYjA5NDE4YjdiMmU5NzViYjU1MDI3ZDRhYjM3NGJlZTI4N2ViM2NiZDA5ZTI2YTM5NzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CebFTgntzgGeh6hXZGS9spSVpEWsaJhYwgO-ynC4NHs">
> 
> > Also please don't put everything on me here.
> 
> I'm sorry for stressing you. I really tried to avoid putting everything on you, but unfortunately I had no luck with the following:
> 
> 1. Asking also @MervinHernandez and @patriciabt for feedback in one of my first comments on this PR, with no luck.
> 2. Writing a comment on gatherpress.org on the weekly huddle 10 days ago, to gather more feedback from the whole team and everybody who might be interested, but this comment is still awaiting moderation.
> 
> > It is best to post any questions in the Slack where there are more people that can assist.
> 
> I'm not able to join the conversation on slack, due to some 🍍🍕🤡, sorry.

I made the comment and didn't click the "submit." I have huge issues with this GitHub UI as it doesn't give clear indication that you didn't click it.

2025-07-22 10:34 UTC, mauteri commented
> Hello @mauteri, thanks for your fast reply!
> 
> 
> 
> > I answer everything I thought (I don't see any outstanding question). 
> 
> 
> 
> It looks different to me, allow me to add some screens of what I mean and like to get your opinion on:
> 
> 
> 
> 1. <img width="1157" height="675" alt="image" src="https://github.com/user-attachments/assets/5e6cd8ab-66b6-494a-9df0-548dbbe24508" />
> 
> 
> 
> ---
> 
> 
> 
> 2. <img width="1157" height="635" alt="image" src="https://github.com/user-attachments/assets/6eed6428-25df-4258-b6e6-216f0de45400" />
> 
> 
> 
> ---
> 
> 
> 
> 3. <img width="1157" height="119" alt="image" src="https://github.com/user-attachments/assets/7c1f6db0-dd37-4ec6-9dbc-23dfe6cdead6" />
> 
> 
> 
> ---
> 
> 
> 
> > Also please don't put everything on me here. 
> 
> 
> 
> I'm sorry for stressing you. I really tried to avoid putting everything on you, but unfortunately I had no luck with the following:
> 
> 
> 
> 1. Asking also @MervinHernandez and @patriciabt for feedback in one of my first comments on this PR, with no luck.
> 
> 2. Writing a comment on gatherpress.org on the weekly huddle 10 days ago, to gather more feedback from the whole team and everybody who might be interested, but this comment is still awaiting moderation.
> 
> 
> 
> > It is best to post any questions in the Slack where there are more people that can assist.
> 
> 
> 
> I'm not able to join the conversation on slack, due to some 🍍🍕🤡, sorry.
> 
> 
> 
> 

What about the internal GatherPress slack? We use the more than the Slack you are referring to.

2025-07-22 12:44 UTC, carstingaxion commented on src/variations/event-query/components/event-order-controls.js
> +					// },
> I could see a filter by author if 2 or more people are holding events for different groups of people on the same site.

An author filter is already available:

<img width="807" height="780" alt="image" src="https://github.com/user-attachments/assets/aa2c91f6-8957-472a-8a15-656060048d9e" />

2025-07-23 15:37 UTC, JordanPak commented on includes/core/classes/blocks/class-event-query.php
> +	public function init(): void {
Will this need to be independently invoked at some point later on? Normally you don't "hook to hook" (`init` -> `pre_render_block` unless these hooks depend on something that isn't available until `init` (for example). Should these just be in `setup_hooks()` in place of the `PHP_INT_MAX` init action?

2025-07-23 16:41 UTC, carstingaxion commented on includes/core/classes/blocks/class-event-query.php
> +	public function init(): void {
No, it doesn't need to and yes you are right.

By looking at the [code were this originated from](https://github.com/ryanwelcher/advanced-query-loop/blame/27d797d056fef269b8ca5f5c3a332cb21a42a087/includes/query-loop.php#L98), I guess this was made to make sure all possible post types were registered at this point, just to get their names to finally loop through.

But ... Because GatherPress knows the name of its post type already, this can be reduced, like you said.

Thanks @JordanPak, will be fixed soon!

2025-07-27 17:38 UTC, mauteri requested changes

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +				 * @since 1.5
Change to `1.0.0`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +				$filtered_query_args = \apply_filters(
no need for `\` just `apply_filters`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +				// "Hijack the global query. It's a hack, but it works." Ryan Welcher
comments need to have a hard stop, so require `.`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +				global $wp_query;
line break here for readability

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +	 *
add `@since 1.0.0` to all methods in class.

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +	public function query_loop_block_query_vars( array $query, \WP_Block $block ): array {
Don't need `\` for `WP_Block` since you have a `use WP_Block`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +	 * @param \WP_Block $block Block instance.
Remove `\`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +		if ( ! is_array( $block_query ) || ! isset( $block_query['gatherpress_events_query'] ) ) {
Thinking maybe add a constant on the class for `gatherpress_events_query`. See other block classes.

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +		// @see wp-content/plugins/gatherpress/includes/core/classes/class-event-query.php .
Remove space before period

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +		$query_args['order'] = \strtoupper( $block_query['order'] ?? 'ASC' );
More `\`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +		$filtered_query_args = \apply_filters(
Remove `\`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/blocks/class-event-query.php
> +		$filtered_query_args = \apply_filters(
Remove `\`

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/class-event-query.php
> +			$pieces['where'] .= $wpdb->prepare( ' AND %i.%i >= %s', $table, $column, $current );
Let's leave a comment so it's easier to follow.

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/class-event-query.php
> +			$pieces['where'] .= $wpdb->prepare( ' AND %i.%i < %s', $table, $column, $current );
Let's leave a comment so it's easier to follow.

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/class-event-query.php
> +			}
All this needs a lot of testing so we don't create issues elsewhere.

2025-07-27 17:38 UTC, mauteri commented on includes/core/classes/class-event-query.php
> +	protected static function get_datetime_comparison_column( string $type, bool $inclusive ): string {
Let's remove `static` as this is being called with `$this` and is a Singleton.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query-no-results/index.js
> +	// keywords: [__('Page numbers'), __('Pagination')],
Remove commented out code.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query/components.js
> +export const EventOffsetControls = ({ attributes, setAttributes }) => {
Add docblock to this.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query/components.js
> +export const GatherPressQueryControlsSlotFill = () => {
Add docblock to this.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query/components.js
> +export const GatherPressInheritedQueryControlsSlotFill = () => {
Add docblock to this.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query/index.js
> +		perPage: 3,
Is 3 the usual default? Thought it would be 5 or 10 in query loop.

2025-07-27 17:38 UTC, mauteri commented on src/variations/core/query/index.js
> +				['core/post-terms', { term: '_gatherpress_venue' }],
We'll do more work on this in `0.34.0` when more blocks are compatible. I did test Event Date and didn't experience any issues. I think I saw a message where you said there was an issue with it.

2025-07-27 17:38 UTC, mauteri commented on test/unit/php/includes/tests/core/classes/class-test-event-query.php
> +		\set_current_screen( 'edit-gatherpress_event' );
Remove `\`

2025-07-27 20:41 UTC, carstingaxion commented on includes/core/classes/blocks/class-event-query.php
> +		if ( ! is_array( $block_query ) || ! isset( $block_query['gatherpress_events_query'] ) ) {
I added a const for 'gatherpress-event-query' as BLOCK_NAME (like in other block classes).

But this here relates to the query param, which has no class constant (yet).
Mention the plural in 'gatherpress_events_query'.

2025-07-27 20:55 UTC, carstingaxion commented on includes/core/classes/class-event-query.php
> +			}
Yes! Feel free to add some unit tests if you can.

2025-07-27 20:57 UTC, carstingaxion commented on src/variations/core/query/index.js
> +				['core/post-terms', { term: '_gatherpress_venue' }],
For me, the "Event date" blocks keeps "being" a loading-spinner on the backend. The comment is over here: https://github.com/GatherPress/gatherpress/issues/1124#issuecomment-3117435844

2025-07-27 20:58 UTC, carstingaxion commented on src/variations/core/query/index.js
> +		perPage: 3,
You are right, this seems to be some left-over from the development.

What is the default of the "Event-list" block? Should be the same, I think.

2025-07-27 21:16 UTC, mauteri commented on src/variations/core/query/index.js
> +		perPage: 3,
Should be same

2025-07-27 21:16 UTC, mauteri commented on src/variations/core/query/index.js
> +				['core/post-terms', { term: '_gatherpress_venue' }],
Can you do a quick Loom? Maybe I'm doing something different and not considering something.

2025-07-28 01:24 UTC, carstingaxion commented on src/variations/core/query/index.js
> +				['core/post-terms', { term: '_gatherpress_venue' }],
I think I don't need to.

All tests I did (in preparation for a *loom*) went positive, in Playground and locally.
Seems to be solved,

2025-07-31 15:55 UTC, carstingaxion commented
Sometimes I can understand your confusion about the GitHub UI @mauteri 

Like currently where it says:
  
  > Changes reviewed
  1 change requested by reviewers with write access.

and shows that there are no open conversations.

  <img width="540" height="310" alt="Bildschirmfoto vom 2025-07-31 17-50-45" src="https://github.com/user-attachments/assets/1fe2ab7e-009d-41aa-82df-828b5dfde1dc" />

---

**How do I get this PR into the final stage** and where is this _1 change requested by reviewers with write access_?

2025-08-01 16:43 UTC, mauteri commented
@carstingaxion I'll look to do final review and get this merged within next few days.

2025-08-02 00:07 UTC, mauteri approved these changes

2025-08-02 00:07 UTC, merged

2025-08-02 07:03 UTC, carstingaxion commented
I can't believe it is merged. Finally and even without additional change-requests. Thanks @mauteri .

2025-08-02 10:53 UTC, mauteri commented
@carstingaxion you're acting like I didn't already leave you a couple rounds of feedback 😂 Nice job on this!

2025-08-03 19:15 UTC, carstingaxion commented
> @carstingaxion you're acting like I didn't already leave you a couple rounds of feedback 😂 Nice job on this!

I'm sorry @mauteri, I meant this in reply to your last comment, where you said 'it'll take some days to prepare a final review'. I was absolutely sure, that there will be some things to change. That's why I -totally surprised- said, there were no changes requested.

Thank you very much for all the many feedback you gave @mauteri, it helped me and the result a lot!

2025-08-03 19:59 UTC, mauteri commented
> > @carstingaxion you're acting like I didn't already leave you a couple rounds of feedback 😂 Nice job on this!
> 
> I'm sorry @mauteri, I meant this in reply to your last comment, where you said 'it'll take some days to prepare a final review'. I was absolutely sure, that there will be some things to change. That's why I -totally surprised- said, there were no changes requested.
> 
> Thank you very much for all the many feedback you gave @mauteri, it helped me and the result a lot!

Haha, no problem. I found some time so I seized it to review your PR :-)